# Generated by Django 4.2.2 on 2023-06-29 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todoitem",
            name="id",
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
