# Generated by Django 4.2 on 2023-05-13 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("todo", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="todo",
            name="description",
        ),
        migrations.AlterField(
            model_name="todo",
            name="title",
            field=models.CharField(max_length=250),
        ),
    ]
