# Generated by Django 4.2.2 on 2023-06-26 20:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_todoitem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todoitem',
            old_name='Completed',
            new_name='completed',
        ),
    ]
